name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Build Rust
      run: cargo build --verbose

    - name: Run Tests
      run: cargo test --verbose

    - name: Install Maturin
      run: pip install maturin

    - name: Build Python Extension
      run: maturin develop
